version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app  # Mount only the backend folder into /app
    depends_on:
      - redis
    networks:
      - ev-network
    restart: unless-stopped

    frontend:
      build: ./frontend
      ports:
        - "3000:3000"  # Expose React Dev Server
      volumes:
        - ./frontend:/app  # Mount frontend source code
        - /app/node_modules  # Prevent overwriting node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true  # Ensures hot reloading works inside Docker
      networks:
        - ev-network
      restart: unless-stopped


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ev-network
  
  data-loader:
    build: ./backend/data-loader
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - ev-network

volumes:
  redis-data:

networks:
  ev-network:
    driver: bridge
